const states = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Georgia: 'GA',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Kentucky: 'KY',
  Maine: 'ME',
  Michigan: 'MI',
  Minnesota: 'MN',
  Montana: 'MT',
  Nevada: 'NV',
  New_Hampshire: 'NH',
  New_Mexico: 'NM',
  New_York: 'NY',
  North_Carolina: 'NC',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Pennsylvania: 'PA',
  South_Dakota: 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  Virginia: 'VA',
  Washington: 'WA',
  West_Virginia: 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY'
}

module.exports = states;
